### ISSUE TITLE
Działanie 

### ISSUE THREAD

**Issue by Spyrox99** [mikolajkalwa/x-kom-Goracy-strzal#3]
Nie jestem zbytnio zaznajomiony z takowymi skryptami. Można wiedzieć jak to uruchomić? Po dodaniu webhooka i uruchomieniu app.js wyskakuje tylko błąd skryptu, błąd składni

**Comment by mikolajkalwa** [comment]
Jak dokładnie brzmi komunikat błędu? @Spyrox99 
W najbliższym czasie dodam instrukcje do readme.

**Comment by Spyrox99** [comment]
![image](https://user-images.githubusercontent.com/36592378/65963674-938a9300-e45b-11e9-9401-58b2d14c2ad2.png)

**Comment by mikolajkalwa** [comment]
Zaktualizowałem [plik z instrukcją](https://github.com/mikolajkalwa/x-kom-Goracy-strzal/blob/master/README.md)
